version: '3'
services:
  app:
    build:
     context: .
     dockerfile: php/Dockerfile
    volumes:
       - ../project/:/var/www/app/
  web:
    build:
     context: .
     dockerfile: server/Dockerfile
    volumes:
       - ../project:/var/www/app/
       - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
       - "127.0.5.5:8080:80"
    networks:
      default:
        aliases:
          - pokemon.service.locale
    links:
      - app
  db:
    image: mysql:8.0.21
    ports:
      - "127.0.5.5:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: owner
      MYSQL_DATABASE: pokeDb
    links:
      - web
networks:
  default:
    external:
      name: pokemon_net
